# Generated by Django 4.0.6 on 2022-07-12 14:18

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_teplo', '0002_articles_delete_heat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
