# Generated by Django 4.0.6 on 2022-07-12 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('get_teplo', '0003_alter_articles_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='date',
        ),
        migrations.AddField(
            model_name='articles',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
