# Generated by Django 4.0.6 on 2022-07-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_teplo', '0004_remove_articles_date_articles_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='url',
            field=models.SlugField(default='coc'),
        ),
    ]
